### ISSUE TITLE
Redirect is not properly configured

### ISSUE THREAD

**Issue by GoogleCodeExporter** [pmonks/alfresco-bulk-filesystem-import#152]
```
In "BulkFilesystemImportWebScript.java", at the end of web script, i see this 
code:

// If successful, redirect to the status Web Script
status.setCode(Status.STATUS_MOVED_TEMPORARILY);
status.setRedirect(true);
status.setLocation(request.getServiceContextPath() + 
WEB_SCRIPT_URI_BULK_FILESYSTEM_IMPORT_STATUS);

I have two considerations:
1) if a call from share: "/share/proxy/alfresco/bulkfsimport/initiate" with 
ajax request, i have a 302 redirect on "/alfresco/s/bulkfsimport/status", but i 
not logged on alfresco! In my opinion, redirect should be done on same 
"context" of original request (in this case, 
"/share/proxy/alfresco/bulkfsimport/status")

2) in some case, i don't need to redirect to status ws. For example, in my 
project, i want call "initiate" with ajax and after i want call "status.xml" 
with ajax. i don't need redirect. I propose a parameter to disable redirect.

```

Original issue reported on code.google.com by `federico...@gmail.com` on 25 Nov 2014 at 12:32

**Comment by tim1234ltp** [comment]
Greetings, I am experiencing the same issue in Alfresco Community Edition 5.2 too without using pmonks' amp. Therefore, I suggested that the issue rather comes from Alfresco itself. 

Here is my case:
I used curl to do POST request on http://yourServer.com:8080/alfresco/s/bulkfsimport/initiate with required form data parameters passed (running as admin). It gave me the following error as it attempted to redirect the page to /alfresco/s/bulkfsimport/status

> The Web Script /alfresco/s/bulkfsimport/initiate has responded with a status of 302 - Moved Temporarily.

> 302 Description:
The resource has temporarily moved to another location, but that future references should still use the original URI to access the resource.

I guess the reason is that when using non-browser approach to GET the redirected status page, Alfresco seemed not able to handle such situation. I am not sure as I am new to Alfresco. If anyone solved this problem, please leave your case here. Thank you.

**Comment by pmonks** [comment]
If you're using URI paths of the form `/bulkfsimport/` then you're using the embedded fork of the tool, _not_ the version hosted here (which has URI paths of the form `/bulk/import/`).

Please see [the wiki](https://github.com/pmonks/alfresco-bulk-import/wiki/Troubleshooting#embedded-fork) for details on why this is not recommended.
